### ISSUE TITLE
Класи тривог

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/SCADA-HMI#2]
- [x] Чому класи тривог не вказуються на дисплеях тривог?
- [x] Класи передбачається для використання тільки в проектуванні і керування змінами? Чи є такі атрибути в стандарті?

**Comment by AlonaShak** [comment]
@pupenasan Класи тривог можуть вказуватися на дисплеях тривог як рекомендація:
An alarm record should have the following alarm record elements:
a)	 process value at the time when the alarm record is recorded,
b)	 alarm setpoint,
c)	 alarm group or process area,
d)	 **alarm class(es),** and
e)	 alarm message.
Клас тривоги дуже сильно зав'язаний з пріоритетом (тому його необов'язково відображати). Пов'язаний з пріоритетом тим, що клас обирається дивлячись на два фактори: 
1) метод ідентифікації (джерело ідентифікації тривоги) : Hazard and Operability Analysis, Safety Requirements Specification, and Failure Modes and Effects Analysis, інші нормативні вимоги, технологічна документація.
2) наслідки.
Пріоритет в свою чергу також обирається враховуючи наслідки та допустимий час реагування.

Також можна обирати на проект один клас, який називають "GENERAL". 
Клас - це атрибут , такий як уставка , пріоритет і т.п.
